CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT NOT NULL,
    status       TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    next_item_id BIGINT NOT NULL,
    version      BIGINT NOT NULL
);

CREATE TABLE order_items (
    order_id    BIGINT NOT NULL,
    item_id     BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    name        TEXT NOT NULL,
    price       DOUBLE PRECISION NOT NULL,
    quantity    BIGINT NOT NULL,

    PRIMARY KEY (order_id, item_id),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);